### ISSUE TITLE
Incorrect encoding when build report with newman allure reporter

### ISSUE THREAD

**Issue by slimp-r** [ervirendersingh/newman-reporter-allure#5]
I'm using Postman with requests containing Cyrillic names:

`
{
	"info": {
		"_postman_id": "fbd11d86-ddb2-4cde-bde7-5ee1809b35ec",
		"name": "Тестовые запросы. ",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Авторизация Copy",
....
`

When I build report I've got the following output in json files
`
"start":1590710240629,"name":"|0x0410|0x0432|0x0442|0x043e|0x0440|0x0438|0x0437|0x0430|0x0446|0x0438|0x044f Copy","descriptionHtml"
`
Do you have option or how to have change encoding for correct displaying results on generating report?

Also I don't see parameters in POST requests in the report...

**Comment by ervirendersingh** [comment]
fixed issue in 1.0.7. now correct data will be displayed.
For parameters, i'll push in another change. Thanks

**Comment by artoffwar** [comment]
> fixed issue in 1.0.7. now correct data will be displayed.
> For parameters, i'll push in another change. Thanks
Hi! The problem described above was not solved. Also, when using Cyrillic, the text is displayed incorrectly, in the form of Unicode characters. 
When the report is generated, the contents of the generated json of the following files: 
	"uuid": "cdf20455-ec86-4fd0-b678-1cece2d27d00",
	"historyId": "79521a9e16500ebc4c87a9c35c55632f",
	"status": "failed",
	"statusDetails": {
		"message": "**|0x0411|0x0418|0x041a |0x043e|0x043f|0x0440|0x0435|0x0434|0x0435|0x043b|0x0451|0x043d**"

If you run tests in Newman, the Cyrillic alphabet is displayed correctly.

**Comment by artoffwar** [comment]
> I'm using Postman with requests containing Cyrillic names:
> 
> `{ "info": { "_postman_id": "fbd11d86-ddb2-4cde-bde7-5ee1809b35ec", "name": "Тестовые запросы. ", "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json" }, "item": [ { "name": "Авторизация Copy", ....`
> 
> When I build report I've got the following output in json files
> `"start":1590710240629,"name":"|0x0410|0x0432|0x0442|0x043e|0x0440|0x0438|0x0437|0x0430|0x0446|0x0438|0x044f Copy","descriptionHtml"`
> Do you have option or how to have change encoding for correct displaying results on generating report?
> 
> Also I don't see parameters in POST requests in the report...

Привет! Тоже столкнулся с аналогичной ситуацией. Подскажи, есть ли возможность как-то связаться (skype, telegram и т.п.) чтобы обсудить и поделиться опытом?

**Comment by alexwishes** [comment]
I have corrected this problem by commenting line 387 and pack this plugin again. 
You can have a try.

**Comment by artoffwar** [comment]
> I have corrected this problem by commenting line 387 and pack this plugin again.
> You can have a try.
The fix still doesn't work.
![image](https://user-images.githubusercontent.com/49728126/92406754-21c1cb80-f139-11ea-81ca-50aa7976e7f4.png)

**Comment by Belamstel** [comment]
Я так понимаю автор забил на свой плагин? и решения проблемы кроме использования латиницы вместо кириллицы нет?

**Comment by Belamstel** [comment]
> > I'm using Postman with requests containing Cyrillic names:
> > `{ "info": { "_postman_id": "fbd11d86-ddb2-4cde-bde7-5ee1809b35ec", "name": "Тестовые запросы. ", "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json" }, "item": [ { "name": "Авторизация Copy", ....`
> > When I build report I've got the following output in json files
> > `"start":1590710240629,"name":"|0x0410|0x0432|0x0442|0x043e|0x0440|0x0438|0x0437|0x0430|0x0446|0x0438|0x044f Copy","descriptionHtml"`
> > Do you have option or how to have change encoding for correct displaying results on generating report?
> > Also I don't see parameters in POST requests in the report...
> 
> Привет! Тоже столкнулся с аналогичной ситуацией. Подскажи, есть ли возможность как-то связаться (skype, telegram и т.п.) чтобы обсудить и поделиться опытом?

Привет. Решения пробемы кроме использования латиницы не появилось?

**Comment by vovsemenv** [comment]
Hello, this repo will be archived. New versions of the newman-reporter-allure will be maintained in the allure framework repo. https://github.com/allure-framework/allure-js

This issue will be fixed soon. New issue for this problem is https://github.com/allure-framework/allure-js/issues/550
